"""CLI option rows owned by the BasicVSR++ family."""

from kinovsr.cli.options import Opt

BASICVSRPP_RESTORE_OPTIONS = [
    Opt(flag='--restore',
        group='Temporal Restore And Deflicker',
        default='off',
        metavar='off|VARIANT',
        profile_tokens=('decompress_track1', 'decompress_track2',
                        'decompress_track3', 'denoise', 'deblur_dvd',
                        'deblur_gopro'),
        family='restore',
        compositional=True,
        help="Pre-upscale TEMPORAL restoration (BasicVSR++, recurrent). Unlike the per-frame deblock/denoise stages, this is bidirectional + second-order over a frame window, so it enforces frame-to-frame consistency -- the fix for GOP-periodic compression flicker (artifacts that appear/disappear between keyframes) and temporally-varying sensor noise that per-frame models pulse on. Runs FIRST by default (before deblock/denoise/nafnet) so it stabilizes the sequence before any per-frame stage. Accepts a COMMA-SEPARATED list to chain restorers in one pass, in order -- e.g. 'decompress_track1,denoise' runs temporal deblock then temporal denoise. Variants: off (default); decompress_track1 (NTIRE'21 compressed-video enhancement, the H.264/HEVC deblock choice) / decompress_track2 / decompress_track3; denoise (temporal video denoise -- softens far less than a per-frame denoiser); deblur_dvd / deblur_gopro (real / synthetic motion deblur). Weights downloaded, not bundled -- see basicvsrpp/weights/README.md. Domain note: trained on HEVC/synthetic degradations, so temporal-right but domain-approximate for 2010-era H.264."),
    Opt(flag='--restore-weights',
        group='Temporal Restore And Deflicker',
        metavar='PATH',
        family='restore',
        key='weights',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        settings_backed=True,
        help="Explicit .safetensors path for --restore (or $BASICVSRPP_RESTORE_WEIGHTS). Use --restore to select a named checkpoint profile."),
    Opt(flag='--restore-strength',
        group='Temporal Restore And Deflicker',
        default='1.0',
        metavar='S[,S...]',
        family='restore',
        key='strength',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        help='Blend each restored frame with the original (1.0 = full restore, default; 0.0 = passthrough). A single value applies to every chained --restore stage; a comma-separated list sets per-stage strengths in order and must match the number of --restore variants -- e.g. --restore decompress_track1,denoise --restore-strength 1.0,0.5 = full deblock then a gentle denoise.'),
    Opt(flag='--restore-window',
        group='Temporal Restore And Deflicker',
        type=int,
        default=14,
        metavar='N',
        family='restore',
        key='window',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        help='Sliding-window length (frames) for --restore recurrence (default 14). Longer = more temporal context (better consistency) but more memory/compute.'),
    Opt(flag='--restore-trim',
        group='Temporal Restore And Deflicker',
        type=int,
        default=2,
        metavar='N',
        family='restore',
        key='trim',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        help="Warm-up frames trimmed at each --restore window join (default 2); the propagation's transient edge. Interior frames match the full-clip result."),
    Opt(flag='--restore-flow',
        group='Temporal Restore And Deflicker',
        default='spynet',
        choices=('spynet', 'zero', 'vt', 'vision'),
        family='restore',
        key='flow',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        help='Optical-flow source for --restore alignment: spynet (default, the trained flow net), zero (no motion), or vt (VideoToolbox flow).'),
    Opt(flag='--restore-ensemble',
        group='Temporal Restore And Deflicker',
        kind='flag',
        default=False,
        family='restore',
        key='ensemble',
        stage_processor='basicvsrpp',
        stage_capabilities=('restore',),
        help="Run --restore through the reference's 8-way geometric self-ensemble (the SpatialTemporalEnsemble the NTIRE decompress/ntire-vsr configs apply at inference, dropped as dead config in the mmagic re-port): restore under 8 flip/rotate variants and average. Cancels orientation-specific hallucinated texture -- measured ~2.5x less flat-region 'alligator skin' and ~1.7x less temporal crawl on the aggressive decompress_track2 -- at 8x the compute. Off by default; worth it when a variant hallucinates on smooth surfaces and you still want its aggression. Applies to every chained --restore stage."),
]

BASICVSRPP_UPSCALE_OPTIONS = [
    Opt(flag='--basicvsrpp-profile',
        group='Spatial Upscalers',
        default='vimeo90k_bd',
        choices=('reds4', 'vimeo90k_bi', 'vimeo90k_bd', 'ntire_vsr'),
        family='basicvsrpp',
        key='profile',
        stage_capabilities=('upscale',),
        help='Which bundled BasicVSR++ 4x checkpoint for --upscale basicvsrpp. All are bicubic/blur-degradation SR models. ntire_vsr = the big c128n25 model (sharpest, 175MB, more memory); vimeo90k_bd (default) = blur-downsample, the best of the small c64n7 models on native footage; vimeo90k_bi / reds4 = bicubic, softer on non-bicubic input. Ignored when --basicvsrpp-weights is given.'),
    Opt(flag='--basicvsrpp-weights',
        group='Spatial Upscalers',
        metavar='PATH',
        family='basicvsrpp',
        key='weights',
        stage_capabilities=('upscale',),
        settings_backed=True,
        help='Explicit BasicVSR++ .safetensors path for --upscale basicvsrpp. Overrides --basicvsrpp-profile (or $BASICVSRPP_WEIGHTS).'),
    Opt(flag='--basicvsrpp-window',
        group='Spatial Upscalers',
        type=int,
        default=14,
        metavar='N',
        family='basicvsrpp',
        key='window',
        stage_capabilities=('upscale',),
        help='Sliding-window length (frames) for --upscale basicvsrpp. The recurrent net is run per window; larger = closer to whole-clip quality but more memory + compute (default 14). Clips shorter than this are processed whole.'),
    Opt(flag='--basicvsrpp-trim',
        group='Spatial Upscalers',
        type=int,
        default=2,
        metavar='N',
        family='basicvsrpp',
        key='trim',
        stage_capabilities=('upscale',),
        help='Warm-up frames trimmed at each window join for --upscale basicvsrpp (default 2). Trimmed frames are re-emitted by the neighbouring window with fuller propagation context.'),
    Opt(flag='--basicvsrpp-ensemble',
        group='Spatial Upscalers',
        kind='flag',
        default=False,
        family='basicvsrpp',
        key='ensemble',
        stage_capabilities=('upscale',),
        help="Run --upscale basicvsrpp through the reference's 8-way geometric self-ensemble (average the 8 flip/rotate variants). The ntire_vsr checkpoint's config declares this SpatialTemporalEnsemble at inference (the reds4/vimeo SR models do not); the mmagic re-port dropped it as dead config. Reference-faithful for ntire_vsr and a mild artifact-reducer, at 8x the compute. Off by default."),
    Opt(flag='--basicvsrpp-flow',
        group='Spatial Upscalers',
        default='spynet',
        choices=('spynet', 'zero', 'vt', 'vision'),
        family='basicvsrpp',
        key='flow',
        stage_capabilities=('upscale',),
        help='Optical-flow source for --upscale basicvsrpp (default spynet). zero disables motion compensation while keeping recurrent propagation, as a control for flow-painted temporal artifacts. vt uses VTOpticalFlow (Quality tier, self-tested at startup; smooth fields, no content-shaped flow noise). vision uses Vision optical flow revision 1 (Medium accuracy, pinned; self-tested at startup) -- the best measured flow backend: sharper true motion than vt at a fraction of its latency, accurate at small sizes where vt collapses, and off the MLX GPU queue.'),
    Opt(flag='--basicvsrpp-history-strength',
        group='Spatial Upscalers',
        type=float,
        default=1.0,
        metavar='S',
        family='basicvsrpp',
        key='history_strength',
        stage_capabilities=('upscale',),
        help="Scale BasicVSR++'s aligned propagation features (default 1.0 = reference strength). 0 disables temporal propagation entirely."),
    Opt(flag='--basicvsrpp-history-gate',
        group='Spatial Upscalers',
        default='off',
        choices=('off', 'improve'),
        family='basicvsrpp',
        key='history_gate',
        stage_capabilities=('upscale',),
        help="Per-pixel history admission for BasicVSR++'s propagation (default off = reference behavior). improve admits aligned history only where the flow warp measurably improves the photometric residual against the current frame; second-order sources gate with the better of their two flows. Mitigates propagation ghosting on content optical flow cannot explain."),
]

__all__ = ["BASICVSRPP_RESTORE_OPTIONS", "BASICVSRPP_UPSCALE_OPTIONS"]
