"""CLI option rows owned by the RealViformer family."""

from kinovsr.cli.options import Opt

REALVIFORMER_OPTIONS = [
    Opt(flag='--realviformer-weights',
        group='Spatial Upscalers',
        metavar='PATH',
        family='realviformer',
        key='weights',
        settings_backed=True,
        help='RealViformer weights path (.safetensors) for --upscale realviformer (or $REALVIFORMER_WEIGHTS). A causal recurrent real-world 4x video upscaler (channel-attention transformer); streams frame by frame with temporal state, reset at cuts. Not bundled; see kinovsr/processors/realviformer/weights/README.md.'),
    Opt(flag='--realviformer-profile',
        group='Spatial Upscalers',
        choices=('x4',),
        family='realviformer',
        key='profile',
        help='Which RealViformer model for --upscale realviformer (x4 = the released real-world 4x checkpoint, default). Ignored when --realviformer-weights is given.'),
    Opt(flag='--realviformer-dtype',
        group='Spatial Upscalers',
        default='float16',
        choices=('float16', 'float32'),
        family='realviformer',
        key='dtype',
        help='Compute/weight dtype for --upscale realviformer. float16 is the default MLX fast path; float32 is closer to the PyTorch reference and useful when isolating recurrent-flow artifacts.'),
    Opt(flag='--realviformer-window',
        group='Spatial Upscalers',
        type=int,
        default=100,
        metavar='N',
        family='realviformer',
        key='window',
        help="Recurrence chunk length (frames) for --upscale realviformer: the temporal state resets cold every N frames, matching the reference inference's 100-frame chunking (default 100). The reset caps the texture-lock etching that unbounded recurrence engraves on long static shots, at the cost of a texture refresh at each chunk join (the reference tool has the same one). 0 = never reset: unbounded streaming recurrence, deeper temporal lock than the released tool ever runs."),
    Opt(flag='--realviformer-flow',
        aliases=('--realviformer-flow-mode',),
        group='Spatial Upscalers',
        default='spynet',
        choices=('spynet', 'zero', 'vt'),
        family='realviformer',
        key='flow',
        help='Optical-flow source for --upscale realviformer (default spynet). zero disables motion compensation while keeping recurrent state, as a control for flow-painted etching; vt uses VideoToolbox VTOpticalFlow in the current-to-previous warp convention.'),
    Opt(flag='--realviformer-history-strength',
        group='Spatial Upscalers',
        type=float,
        default=1.0,
        metavar='S',
        family='realviformer',
        key='history_strength',
        help="Scale RealViformer's normalized propagated-history branch before the merge FFN (default 1.0 = reference strength). 0 disables temporal history while still exercising the recurrent code path; values below 1 soften temporal etching."),
    Opt(flag='--realviformer-history-gate',
        group='Spatial Upscalers',
        default='off',
        choices=('off', 'improve', 'holistic'),
        family='realviformer',
        key='history_gate',
        help='History confidence gate for --upscale realviformer. off = reference merge. improve = pass history only where the flow-warped previous RGB frame improves the current-vs-previous residual; this drops ambiguous near-static/compressed regions that otherwise etch. holistic = opt-in HSA-lite risk policy: relative warp benefit + match confidence + risk memory, with optional hidden-state cleanup.'),
    Opt(flag='--realviformer-history-cleanup',
        group='Spatial Upscalers',
        type=float,
        default=0.25,
        metavar='S',
        family='realviformer',
        key='history_cleanup',
        help='For --realviformer-history-gate holistic, max blend toward a 3x3 box-blurred warped hidden state in risky regions (default 0.25).'),
    Opt(flag='--realviformer-history-gate-drop',
        group='Spatial Upscalers',
        type=float,
        default=0.85,
        metavar='S',
        family='realviformer',
        key='history_gate_drop',
        help='For --realviformer-history-gate holistic, max fraction of temporal history gate removed in risky regions (default 0.85).'),
    Opt(flag='--realviformer-history-risk-decay',
        group='Spatial Upscalers',
        type=float,
        default=0.8,
        metavar='S',
        family='realviformer',
        key='history_risk_decay',
        help='For --realviformer-history-gate holistic, decay for the flow-warped risk memory between frames (default 0.80; must be <1).'),
    Opt(flag='--realviformer-history-static-cap',
        group='Spatial Upscalers',
        type=float,
        default=0.0,
        metavar='S',
        family='realviformer',
        key='history_static_cap',
        help='For --realviformer-history-gate holistic, capped confidence admitted for perfectly static regions (default 0.0 until long-static etch tests prove a nonzero cap is safe).'),
]

__all__ = ["REALVIFORMER_OPTIONS"]
