"""CLI option rows owned by the deflicker family."""

from kinovsr.cli.options import Opt

DEFLICKER_OPTIONS = [
    Opt(flag='--deflicker',
        group='Temporal Restore And Deflicker',
        default='off',
        choices=('off', 'on'),
        family='deflicker',
        help='Verified-static temporal state integration, run before deblock/denoise. For starved, loop-filtered encodes whose damage is temporally UNSTABLE quantization states on static content (GOP pulses, coding-cadence flicker, re-quantization flashes): integrates each pixel over a +/-window trajectory, but ONLY where phase correlation verifies the surrounding 32px tiles as static between the two frames -- moving content is passthrough BY CONSTRUCTION, and nothing is ever warped, so misalignment cannot smear. A pixel is only ever replaced by an average of its own trajectory samples (no spatial mixing: no softening budget); real content changes are one-sided in time and refuse the two-sided consensus gate. Lets --denoise run gentler on compressed junk.'),
    Opt(flag='--deflicker-window',
        group='Temporal Restore And Deflicker',
        type=int,
        default=8,
        metavar='K',
        family='deflicker',
        key='window',
        help='Temporal integration half-window in frames (default 8: covers typical GOP-pulse cadences; also the stage latency). Larger = stabler + slower; must exceed the flicker period to collapse it.'),
    Opt(flag='--deflicker-band',
        group='Temporal Restore And Deflicker',
        type=float,
        default=0.1,
        metavar='H',
        family='deflicker',
        key='band',
        help='Luma half-width around the window median that counts as the same quantization-state cluster (default 0.10). Measured on real crushed footage this knob is nearly inert above ~0.08: the correction is dominated by the dense state-wobble cluster around the median, which any band covering it yields identically, and the rare far states barely move the mean. Its only active range is downward -- drop toward 0.05 if legitimate low-contrast motion is being stabilized. The levers that actually scale the effect are --deflicker-window and --deflicker-strength.'),
    Opt(flag='--deflicker-strength',
        group='Temporal Restore And Deflicker',
        type=float,
        default=1.0,
        metavar='A',
        family='deflicker',
        key='strength',
        help='Blend of the stabilized value. 1.0 (default) = full replacement with the dwell-weighted state mixture, which is already the maximum meaningful effect; values above 1.0 overshoot PAST the estimate and re-inject the artifact in antiphase (manufactured inverted flicker). Lower below 1.0 to dial the look back.'),
    Opt(flag='--deflicker-frac',
        group='Temporal Restore And Deflicker',
        type=float,
        default=0.5,
        metavar='F',
        family='deflicker',
        key='frac',
        help='Fraction of admitted samples that must sit in-band around the window median for a pixel to fire (default 0.5). Lowering fires on weaker consensus: below ~0.4 the protection against real content changes rests on the two-sided gate alone, and mixed junk/content pixels start averaging real change into the output (ghosting at appearance/disappearance edges). Raise toward 0.65 to be extra conservative on busy footage.'),
    Opt(flag='--deflicker-max-fix',
        group='Temporal Restore And Deflicker',
        type=float,
        default=0.25,
        metavar='D',
        family='deflicker',
        key='max_fix',
        help='Corrections larger than this luma delta are REFUSED, not clamped (default 0.25). This is a safety valve, not a strength dial: genuine state flicker sits well below it, so raising it mainly admits corrections that come from misverification or true content changes -- isolated wrong patches and ghosts. Lower it on precious footage; think twice before raising.'),
    Opt(flag='--deflicker-gop',
        group='Temporal Restore And Deflicker',
        default='on',
        choices=('off', 'on'),
        family='deflicker',
        key='gop',
        help="Sync-keyed GOP-pumping rescue (default on). The oscillatory gate refuses single state steps - correctly for unexplained steps, but a window shorter than the source's GOP sees the I-frame pop as exactly one step and never fixes it. When the source's sync flags are available, deltas at declared coding restarts are discounted before the gate re-tests: a flat-step-flat pump profile at an I-frame becomes fixable, while real lighting ramps stay refused (their residual is still monotone) and real light steps that land on an I-frame are still refused by the sign-coherence veto. Turn off to reproduce pre-GOP-aware output exactly."),
    Opt(flag='--deflicker-jitter',
        group='Temporal Restore And Deflicker',
        default='off',
        choices=('off', 'on'),
        family='deflicker',
        key='jitter',
        help="Compensate global camera micro-jitter before static verification: the median per-tile displacement of each frame pair is treated as camera shift, tiles verify against the residual, and admitted samples are aligned by one whole-frame Fourier translation (never per-tile warps). Use when footage is handheld/tripod-bumped and 'static-verified' reads far below the clip's true static fraction -- it widens the tool's scope to jitter-masked static content. Pairs shifted beyond 3px are real camera motion and stay refused. Costs roughly 2x runtime; off (default) is bit-identical to the unjittered path."),
]

__all__ = ["DEFLICKER_OPTIONS"]
