"""CLI option rows owned by shared processor conditioning."""

from kinovsr.cli.options import Opt

DEBLOCK_MAP_OPTIONS = [
    Opt(flag='--deblock-map',
        group='Deblock',
        default='constant',
        choices=('constant', 'auto'),
        family='deblock_map',
        help='Spatial gating for --deblock stdf/fbcnn. constant (default) = the correction applies everywhere at --deblock-strength. auto = estimate a per-pixel blockiness mask from the footage (coding-grid phase detection + boundary-vs-interior gradient contrast; texture and 1D content edges reject) and gate the correction by it -- blocked flats get the full deblock, detailed/clean areas keep their texture.'),
    Opt(flag='--deblock-map-gain',
        group='Deblock',
        type=float,
        default=1.0,
        metavar='G',
        family='deblock_map',
        key='gain',
        help='Multiplier on the auto blockiness mask (default 1.0). >1 saturates the mask sooner (more area fully deblocked); <1 is more conservative. The mask clamps at 1.0 after the gain, so the blend never extrapolates past the deblocked frame. Only used with --deblock-map auto.'),
]

NOISE_MAP_OPTIONS = [
    Opt(flag='--noise-map',
        group='Denoise And Noise Maps',
        default='constant',
        choices=('constant', 'auto'),
        family='noise_map',
        help='Noise conditioning for map-driven denoisers (fastdvdnet, bsvd, pvdd level variants). constant (default) = one sigma everywhere (from --denoise-strength / --pvdd-noise-*). auto = estimate a per-pixel sigma map from the footage itself (temporal frame-difference statistics: texture-safe, motion-capped, smooth), so noisy shadows get denoised harder than clean lit areas. For mc, the map replaces --mc-sigma as the per-pixel residual-rejection scale. Ignored with a warning by denoisers that have no map input (spatial, blind pvdd variants).'),
    Opt(flag='--noise-map-gain',
        group='Denoise And Noise Maps',
        type=float,
        default=1.0,
        metavar='G',
        family='noise_map',
        key='gain',
        help="Multiplier on the auto-estimated noise map (default 1.0). >1 denoises harder everywhere while keeping the spatial shape; <1 is gentler. For fastdvdnet/bsvd the gained map is clamped into the nets' trained sigma range [5/255, 55/255] -- the same span the manual --denoise-strength dial has -- so heavily compressed clips whose measured temporal noise sits below the dial floor get the floor (a mild denoise) instead of a no-op. Only used with --noise-map auto."),
    Opt(flag='--noise-map-debug',
        group='Denoise And Noise Maps',
        kind='flag',
        default=False,
        family='noise_map',
        key='debug',
        help='With --noise-map auto: after the run, write the estimated sigma map as <output>_noisemap.png (grayscale, sigma 0..0.15 -> black..white) and print its stats, so the estimate can be eyeballed.'),
    Opt(flag='--noise-map-refresh',
        group='Denoise And Noise Maps',
        type=int,
        default=64,
        metavar='N',
        family='noise_map',
        key='refresh',
        help='With --noise-map auto in plain streaming mode (fastdvdnet/bsvd without --gop-align): re-estimate the map from the last frames every N input frames, EMA-blended so it adapts without pumping (default 64; 0 = estimate once from the first frames and hold). Windowed modes (--gop-align, pvdd) re-estimate per window and ignore this.'),
    Opt(flag='--noise-map-masking',
        group='Denoise And Noise Maps',
        type=float,
        default=0.0,
        metavar='S',
        family='noise_map',
        key='masking',
        help='Perceptual masking weight for the noise map (default 0 = off; 1 = full). Noise visibility is highest in flat regions and lowest near edges/texture, while over-conditioning near detail reads as softness -- so at 1.0 flat blocks get a ~1.75x suppression margin over the measured amplitude (the visual-kill margin) and detailed blocks are tempered to ~0.5x. Fixes the constant-beats-map case where the map smooths hardest exactly where the eye punishes softness most.'),
    Opt(flag='--noise-map-motion-cap',
        group='Denoise And Noise Maps',
        default='strict',
        choices=('strict', 'loose', 'off'),
        family='noise_map',
        key='motion_cap',
        help="How aggressively the noise map's motion cap suppresses blocks that look motion-like. Temporal statistics cannot separate compression flicker that persists a couple of frames (lag ratio ~1.5) from occlusion edges (~1.41), so this is a material decision: strict (default) = displacement-safe, right for real subject/camera motion; loose = static-camera material, persistent flicker also escapes the cap; off = tripod/archival footage, no cap -- the map reports exactly what it measured."),
    Opt(flag='--noise-map-floor-mode',
        group='Denoise And Noise Maps',
        default='mc',
        choices=('mc', 'flat'),
        family='noise_map',
        key='floor_mode',
        help="Source of the motion-immune noise floor that anchors the map's luma model on moving content. mc (default): 32px blocks are aligned by phase correlation (subpixel) before the whitened residual median, so the floor is read on ALL pixels -- stronger on pans over weak texture where flat pixels are scarce or drift-contaminated, and cheaper. flat: whitened median over gradient-free pixels only (motion cannot flicker flat pixels); the two agree wherever the flat set is healthy."),
    Opt(flag='--noise-map-upsample',
        group='Denoise And Noise Maps',
        default='edge',
        choices=('edge', 'box'),
        family='noise_map',
        key='upsample',
        help="How the coarse sigma grid becomes the per-pixel map. edge (default): CoreImage edge-preserving guided upsample -- the map follows luma edges instead of bleeding sigma across them (18-31 percent lower map error on content-aligned noise fields, exact parity on uniform ones; ~12 ms per map refresh, off the MLX queue). box: the previous repeat + box-blur upsample, kept for comparison and for content whose noise boundaries do not follow luma edges."),
    Opt(flag='--noise-map-floor',
        group='Denoise And Noise Maps',
        type=float,
        default=0.0,
        metavar='S',
        family='noise_map',
        key='floor',
        help="Minimum sigma under the auto noise map (0..1 scale; default 0 = the net's own trained floor, 5/255 for fastdvdnet/bsvd). The temporal estimator measures FLICKERING noise only; static grain, dirt, and structured junk do not flicker and read near zero even though conditioning the denoiser higher visibly cleans them. The floor guarantees a base denoise level -- the role of the manual strength dial -- with the map's spatial and pulse adaptation applying above it. E.g. 0.02 ~= --denoise-strength 0.005, 0.03 ~= 0.1."),
    Opt(flag='--noise-map-pulse',
        group='Denoise And Noise Maps',
        kind='flag',
        default=False,
        family='noise_map',
        key='pulse',
        help="Per-frame gain on the noise conditioning that tracks GOP-phase noise pulsing: old encoders re-code the grain at every I-frame, so temporal noise is elevated right after keyframes and suppressed once P/B prediction settles. Each frame's global sigma is measured against the running settled level and the sigma plane is scaled by the ratio (clamped 0.6..1.8), so I-frame grain refreshes get proportionally stronger denoising. With --noise-map auto, whole-frame pulse spikes are damped out of the base map so they are not counted twice. Works with --noise-map constant or auto; map-conditioned denoisers only (fastdvdnet, bsvd, mc, pvdd level variants)."),
]

__all__ = ["DEBLOCK_MAP_OPTIONS", "NOISE_MAP_OPTIONS"]
