"""CLI option rows owned by the motion-compensated denoiser family."""

from kinovsr.cli.options import Opt

MC_STRENGTH_OPTIONS = [
    Opt(flag='--mc-strength',
        group='Denoise And Noise Maps',
        type=float,
        metavar='S',
        family='mc',
        key='strength',
        help='Strength for --denoise mc (max temporal blend toward motion-compensated history), overriding the positional --denoise-strength value for this family (default: the chain value).'),
]

MC_OPTIONS = [
    Opt(flag='--mc-window',
        group='Denoise And Noise Maps',
        type=int,
        default=0,
        metavar='N',
        family='mc',
        key='window',
        help='mc temporal structure (mutually exclusive). 0 (default) = recursive IIR (blends the previous output; strongest denoise, longest ghosts). N>=1 = causal FIR over the last N input frames (bounded ghost lifetime, ~N optical-flow computes per frame).'),
    Opt(flag='--mc-flow',
        group='Denoise And Noise Maps',
        default='vt',
        choices=('vt', 'spynet'),
        family='mc',
        key='flow',
        help="mc's motion engine. vt (default): VTOpticalFlow Quality tier on CPU/AMX (~17 ms fixed, no GPU contention, mediocre accuracy with smooth errors). spynet: stock BasicSR SpyNet on MLX -- measured +3-5 dB warp-PSNR in every motion regime, so more pixels pass the photometric gate and get denoised (higher ceiling), at the cost of GPU time shared with other stages. Flow errors only lower the ceiling either way: every warp is audited against the current frame before it blends. Watch the end-of-run 'gate openness' number: if it is low, mc is flow-limited and spynet is the lever (raising strength is not)."),
    Opt(flag='--mc-flow-weights',
        dest='spynet_weights',
        group='Denoise And Noise Maps',
        metavar='PATH',
        family='mc',
        key='flow_weights',
        settings_backed=True,
        help='SpyNet weights (.safetensors, spynet.* keys) for --mc-flow spynet. Default: the bundled stock checkpoint (override with this flag or $SPYNET_WEIGHTS). Use a STOCK checkpoint, not one extracted from an SR net: end-to-end training repurposes SpyNet into a feature matcher and its flow accuracy collapses (measured worse than zero flow on static content).'),
    Opt(flag='--mc-gate',
        group='Denoise And Noise Maps',
        default='smooth',
        choices=('smooth', 'curr'),
        family='mc',
        key='gate',
        help="What mc measures each reference's residual against. smooth (default): a 3x3 box mean of the current frame, gate width recalibrated to match -- the anchor's own noise stops randomly opening/closing the gate per pixel, measured +0.2..+0.5 dB on ground truth with ghost rejection intact. curr: legacy, the raw current frame. (Gating against the warped-reference consensus was tried and REFUTED: flow-warp errors correlate across references, so in occlusion regions the consensus IS the ghost.)"),
    Opt(flag='--mc-sigma',
        group='Denoise And Noise Maps',
        type=float,
        default=0.06,
        metavar='S',
        family='mc',
        key='sigma',
        help="mc residual-rejection scale (luma, 0..1; default 0.06 ~= 15/255). The blend gate is exp(-(current-vs-history residual / sigma)^2); noise inflates that residual, so at the default it throttles its own removal even at --denoise-strength 1. RAISE it (e.g. 0.10-0.15) to denoise harder when strength alone plateaus -- the real 'make it stronger' knob for noisy footage. Cost: it also tolerates motion mismatch, so higher = more ghosting/smearing on fast motion. With --noise-map auto this scalar is REPLACED by the estimated per-pixel map (in residual units); scale that with --noise-map-gain instead."),
    Opt(flag='--mc-clamp',
        group='Denoise And Noise Maps',
        kind='flag',
        default=False,
        family='mc',
        key='clamp',
        help="mc: clamp warped history to the current frame's local color box (TAA variance-clip). The strongest single anti-ghost. Combinable."),
    Opt(flag='--mc-occlusion',
        group='Denoise And Noise Maps',
        kind='flag',
        default=False,
        family='mc',
        key='occlusion',
        help='mc: reject history via forward-backward flow consistency (occlusion / bad-flow detection). Combinable.'),
    Opt(flag='--mc-confidence',
        group='Denoise And Noise Maps',
        kind='flag',
        default=False,
        family='mc',
        key='confidence',
        help='mc: down-weight history where flow magnitude is large (fast motion). Combinable.'),
]

__all__ = ["MC_STRENGTH_OPTIONS", "MC_OPTIONS"]
