"""CLI option rows owned by the NAFNet family."""

from kinovsr.cli.options import Opt

NAFNET_OPTIONS = [
    Opt(flag='--nafnet',
        group='NAFNet',
        default='off',
        choices=('off', 'gopro', 'gopro32', 'sidd', 'sidd32', 'reds'),
        family='nafnet',
        help='NAFNet restoration pass, run LAST in the preprocess chain (a light detail/deblur residual after deblock + denoise). off (default); gopro/gopro32 = motion deblur (width 64/32); sidd/sidd32 = real-noise denoise; reds = video restore. Single-image RGB net; weights are downloaded, not bundled (see kinovsr/processors/nafnet/weights/README.md).'),
    Opt(flag='--nafnet-weights',
        group='NAFNet',
        metavar='PATH',
        family='nafnet',
        key='weights',
        settings_backed=True,
        help='NAFNet .safetensors path override for --nafnet (or $NAFNET_WEIGHTS); not bundled.'),
    Opt(flag='--nafnet-strength',
        group='NAFNet',
        type=float,
        default=1.0,
        metavar='A',
        family='nafnet',
        key='strength',
        help="Scale NAFNet's residual for --nafnet: out = input + A*residual. 1.0 = full (default); lower keeps it a LIGHT pass -- recommended on video, since it is a single-image net and a strong pass can flicker. >1 over-drives."),
    Opt(flag='--nafnet-pool',
        group='NAFNet',
        default='auto',
        choices=('auto', 'local', 'global'),
        family='nafnet',
        key='pool',
        help='NAFNet SCA pooling mode. auto (default) follows the reference config for the selected variant: gopro/gopro32/reds use NAFNetLocal TLSC/TLC, sidd/sidd32 use plain global-pool NAFNet. local forces TLSC; global disables TLSC.'),
    Opt(flag='--nafnet-guard',
        group='NAFNet',
        default='auto',
        choices=('auto', 'off', 'residual', 'control', 'control-source', 'fast', 'reject'),
        family='nafnet',
        key='guard',
        help='Guard against out-of-domain NAFNet residual blow-ups. auto (default) uses reject for gopro/gopro32 and off for other variants. reject emits passthrough for frames whose residual explosion covers a visible area, locks the net out after two consecutive such frames (or one catastrophic one), and re-probes on a --nafnet-guard-lockout cadence so a scene change recovers the stage. residual applies a local output-side soft knee; control reruns localized risky frames on a vertically luma-smoothed control input, but locks into control-source if risk is frame-wide. control-source predicts the residual from a stable luma-control input and adds it to the original; fast always uses single-pass residual attenuation.'),
    Opt(flag='--nafnet-guard-threshold',
        group='NAFNet',
        type=float,
        default=0.12,
        metavar='T',
        family='nafnet',
        key='guard_threshold',
        help='Local residual magnitude threshold for --nafnet-guard (default 0.12). Healthy frames skip the guard bit-exactly; lower catches more lattice but can replace more legitimate deblur residual.'),
    Opt(flag='--nafnet-guard-fast-fraction',
        group='NAFNet',
        type=float,
        default=0.85,
        metavar='F',
        family='nafnet',
        key='guard_fast_fraction',
        help='Fraction of frame-risk coverage where control guard switches to a stable control-source residual instead of per-region blending (default 0.85). Set <=0 or >1 to force the slower two-pass regional path.'),
    Opt(flag='--nafnet-guard-lockout',
        group='NAFNet',
        type=int,
        default=48,
        metavar='N',
        family='nafnet',
        key='guard_lockout',
        help='Reject-guard lockout period: frames to hold passthrough between re-probes of the net once the reject guard has locked (default 48, about 1.6-2s). 0 = never re-probe; stay locked for the rest of the clip. Locked frames skip the net entirely, so long lockouts also run faster.'),
    Opt(flag='--nafnet-guard-ramp',
        group='NAFNet',
        type=int,
        default=12,
        metavar='N',
        family='nafnet',
        key='guard_ramp',
        help='Reject-guard transition smoothing: restoration strength eases in over N clean frames (smoothstep, so fades start and stop without a visible temporal edge) and eases OUT on moderate trips instead of cutting to passthrough (default 12; fall length from --nafnet-guard-fall). Catastrophic or large-area explosions still cut instantly. 0 = hard switching both ways.'),
    Opt(flag='--nafnet-guard-fall',
        group='NAFNet',
        type=int,
        metavar='N',
        family='nafnet',
        key='guard_fall',
        help='Frames to fade restoration OUT on a moderate reject-guard trip (the fade emits the knee-damped residual). Default: derived from --nafnet-guard-ramp as ramp/4, min 2. 0 = hard cut on trips while keeping the eased fade-in. Longer = softer off-switch but more frames carrying damped trip residual.'),
]

__all__ = ["NAFNET_OPTIONS"]
