"""Foundation and cross-family slot CLI option rows."""

from .options import Opt, pp_order

SOURCE_AND_OUTPUT_OPTIONS = [
    Opt(flag='--video',
        group='Source Selection',
        required=True,
        help='Video file (mp4/mov/...).'),
    Opt(flag='--reader',
        group='Input Decode',
        default='auto',
        choices=('auto', 'native', 'ffmpeg'),
        help="Video reader backend. auto (default) = the native AVFoundation reader (zero-copy, full precision), falling back to the ffmpeg compatibility reader when the container/codec is refused (MKV, VP9, AVI-era material). ffmpeg = force the compatibility reader (needs PyAV: install the 'ffmpeg' extra). native = never fall back. The ffmpeg reader mirrors color tags, keyframe windows (--gop-align), trims, and audio; its frame indices are self-consistent but may differ from the native reader's by an edit-list offset on the same file."),
    Opt(flag='--output-dir',
        group='Output, Encoding, And Audio',
        help=''),
    Opt(flag='--output-prefix',
        group='Output, Encoding, And Audio',
        default='vsr',
        help='Filename prefix for the timestamped outputs.'),
    Opt(flag='--overwrite',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help='Replace an existing complete artifact set transactionally. Without this flag, any existing or reserved destination is an error.'),
    Opt(flag='--encode-quality',
        group='Output, Encoding, And Audio',
        type=float,
        default=0.65,
        help='AVVideoQualityKey (0..1) for the HEVC encoder. 0.65 matches the default tier.'),
    Opt(flag='--encode-chroma',
        group='Output, Encoding, And Audio',
        default='auto',
        choices=('auto', '420', '422'),
        help='HEVC profile chroma subsampling. auto = 4:2:2 (Main42210) for balanced/image modes, 4:2:0 (Main10) for fast. 420 forces Main10.'),
    Opt(flag='--audio',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help="Mux the source file's audio track into both MP4s. Inputs with no audio track stay silent."),
    Opt(flag='--audio-codec',
        group='Output, Encoding, And Audio',
        default='alac',
        choices=('alac', 'aac'),
        help='Audio codec for muxed audio (alac=lossless, aac=256kbps).'),
    Opt(flag='--save-audio-sidecar',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help='Also write the muxed audio as <stem>_audio.wav next to the MP4s.'),
    Opt(flag='--save-pre-frames',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help=''),
    Opt(flag='--save-post-frames',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help=''),
    Opt(flag='--skip-post-mp4',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help='Skip writing the upscaled _post.mp4 (e.g. when you only want frame dumps).'),
    Opt(flag='--comparison',
        group='Output, Encoding, And Audio',
        kind='flag',
        default=False,
        help='Also write a side-by-side <stem>_comparison.mp4 (NEAREST-upscaled pre vs VSR post).'),
    Opt(flag='--source-color',
        group='Color Interpretation',
        default='auto',
        choices=('auto', 'bt709', 'bt601', 'bt2020'),
        help="How the source is interpreted. auto (default) trusts the container's color tags, or VideoToolbox's resolution guess when untagged (SD width -> BT.601, HD -> BT.709). bt601/bt709/bt2020 FORCE the source to be decoded as that matrix -- the fix for untagged/mistagged clips VT guesses wrong. For balanced/image it decodes raw YUV and re-interprets it (not just an output tag); fast/NV12 keeps VideoToolbox's decode and only re-tags. The output is tagged to match."),
    Opt(flag='--source-range',
        group='Color Interpretation',
        default='auto',
        choices=('auto', 'video', 'full'),
        help="How the source's YUV code values map to RGB. auto (default) trusts the container's range flag (untagged = video/limited range, the standard assumption -- Y 16-235). video/full FORCE the interpretation for mis-flagged sources, e.g. full-range screen recordings or phone/webcam MP4s an encoder left untagged: read as limited they get shadows crushed to black and highlights clipped BEFORE any model runs (and the learned upscalers respond badly to the clipped regions). The reinterpretation is exact -- same decoded code values, different YUV->RGB scaling -- and the output is tagged to match. Not available with --upscale fast (its YUV passes through untouched)."),
    Opt(flag='--start',
        group='Trim, Cropping, And Cuts',
        help='Trim the input to start at this position (process the middle of a clip). Accepts frames or time: bare integer = frames (e.g. 120), Nf = frames (120f), Ns / decimal = seconds (5s, 1.5), or a clock string mm:ss / hh:mm:ss (0:05, 1:02:03). KinoVSR seeks here natively so the head is not decoded.'),
    Opt(flag='--end',
        group='Trim, Cropping, And Cuts',
        help='Trim the input to stop before this position (exclusive), same frames-or-time forms as --start. Output is a fresh clip starting at PTS 0 spanning [--start, --end).'),
    Opt(flag='--max-frames',
        group='Trim, Cropping, And Cuts',
        help='Cap the number of OUTPUT frames. Same frames-or-time forms as --start (a time here is output duration, measured at the target fps). Composes with --start/--end, which trim the input.'),
    Opt(flag='--snap-start',
        group='Trim, Cropping, And Cuts',
        kind='flag',
        default=False,
        help="Snap --start to the nearest source keyframe, so the output actually BEGINS on a clean I-frame (a clean editorial cut, a pristine first frame, and no context-decode overhead). This MOVES the start -- you get a slightly different range than requested -- so it is warned and the effective range is echoed. Contrast --gop-align's anchor, which keeps your exact --start and reads the pre-start frames as context. --video only."),
    Opt(flag='--gop-align',
        group='Trim, Cropping, And Cuts',
        kind='flag',
        default=False,
        family='gop',
        key='align',
        help="Align recurrent windows (--restore and the basicvsrpp/realbasicvsr/realviformer upscalers) to the source's GOP: detect keyframes natively (no ffprobe) and window keyframe-to-keyframe so BOTH recurrence directions cold-start on a clean I-frame -- no warm-up trim needed. Overhead is ~1 re-processed frame per GOP (a few percent) instead of trim's ~2x, and it removes window-boundary flicker on GOP-structured video. Falls back to fixed max-window tiling when the source has no keyframe cadence. --video only. Overrides the per-stage --*-window/-trim."),
    Opt(flag='--gop-min-window',
        group='Trim, Cropping, And Cuts',
        type=int,
        default=16,
        metavar='N',
        family='gop',
        key='min_window',
        help='Minimum recurrent window (frames) under --gop-align (default 16). A window spans whole GOPs until it reaches this, so short GOPs are merged for enough temporal context.'),
    Opt(flag='--gop-max-window',
        group='Trim, Cropping, And Cuts',
        type=int,
        default=96,
        metavar='N',
        family='gop',
        key='max_window',
        help='Maximum recurrent window (frames) under --gop-align (default 96). A GOP longer than this is split into sub-windows (with a small trim at the internal splits) to bound memory.'),
]

PREPROCESS_SLOT_OPTIONS = [
    Opt(flag='--preprocess-order',
        group='Preprocess Ordering',
        type=pp_order,
        metavar='A,B,C',
        help="Explicit order for the preprocess stages, comma-separated from {restore, deflicker, deblock, denoise, nafnet}, e.g. 'deflicker,deblock,denoise'. Only enabled stages run; any enabled stage you omit is appended in the default order (restore, deflicker, deblock, denoise, nafnet). Overrides --denoise-first when set."),
    Opt(flag='--denoise-first',
        group='Preprocess Ordering',
        kind='flag',
        default=False,
        family='denoise',
        key='first',
        help="Run --denoise before --deblock (default is deblock then denoise). The default suits captured-then-encoded footage: undo the last degradation (compression) first, and a denoiser's white-noise assumption is broken by structured blocking. Use --denoise-first only when noise was added AFTER compression (regrained master, analog/transmission noise)."),
]

DEBLOCK_SLOT_OPTIONS = [
    Opt(flag='--deblock',
        group='Deblock',
        default='off',
        metavar='NAME[,NAME...]',
        family='deblock',
        help="Pre-upscale compression-artifact deblock, applied before denoise + VSR (deblock before SR amplifies the blocking). Comma-chain to run several in order (e.g. toflow,stdf: TOFlow's gentle flow-fused pass then STDF's deformable fusion; stages run left to right). off (default); stdf = STDF deformable spatio-temporal fusion (HEVC-trained, luma-only 7-frame window, weights bundled); toflow = the TOFlow deblock checkpoint (task-oriented-flow seven-frame window, weights bundled; heavy -- see --denoise toflow notes; --deblock-strength is its dry/wet blend, --deblock-map does not apply); fbcnn = FBCNN flexible blind JPEG-artifact removal (single-image RGB, ~72M params, weights downloaded not bundled -- see kinovsr/processors/fbcnn/weights/README.md). Routes frames through the MLX path."),
]

DEBLOCK_STRENGTH_OPTIONS = [
    Opt(flag='--deblock-strength',
        group='Deblock',
        default='1.0',
        metavar='S[,S...]',
        family='deblock',
        key='strength',
        help='Scale the deblock effect (1.0 = full, default; lower keeps more fine texture at the cost of less deblocking -- try 0.5-0.7 on faces). With a chained --deblock, give one value per stage (comma list) or one value for all. For stdf this scales the residual; for fbcnn it is the dry/wet blend; for toflow it is the dry/wet blend -- and since the reference network has NO strength conditioning, values above 1.0 EXTRAPOLATE the correction past the trained operating point (measured: 1.3 costs ~0.1 dB, 1.6 ~0.2 dB vs ground truth for visibly harder deblocking; chaining toflow,toflow deepens the cleaning instead at ~0.3 dB/pass). A family-level flag (--stdf-strength, --fbcnn-strength, --toflow-strength) overrides the chain value for that family.'),
]

DENOISE_SLOT_OPTIONS = [
    Opt(flag='--denoise',
        group='Denoise And Noise Maps',
        default='off',
        metavar='NAME[,NAME...]',
        family='denoise',
        help="Pre-upscale denoise, applied at native resolution before VSR (the correct order - SR amplifies noise). Comma-chain to run several in order at low strengths (e.g. mc,bsvd: mc's flow-warped temporal average and bsvd's learned prior remove DIFFERENT noise kinds; the chain runs left to right, each stage feeding the next). off (default); spatial = per-frame CoreImage CINoiseReduction (cheap, no temporal state); mc = motion-compensated temporal denoise via VideoToolbox optical flow (Quality tier plus startup self-test; recursive, GPU; averages static regions over time without ghosting moving edges); fastdvdnet = FastDVDnet CNN denoiser (MLX, learned; causal 5-frame window, strongest denoise, weights bundled); bsvd = BSVD bidirectional-buffer streaming denoiser (MLX, learned; 16-frame delay, weights local); toflow = TOFlow task-oriented-flow denoise/deblock (MLX interpreter for converted Torch7 checkpoints; 7-frame window, blind); pvdd = PVDD real-world denoiser (MLX, learned; bidirectional window attention, real-noise-trained -- unlike the AWGN-trained fastdvdnet/bsvd; --pvdd-profile picks pvdd/crvd/davis, weights local). Enabling denoise routes frames through the MLX upload path instead of the zero-copy direct feed."),
    Opt(flag='--denoise-strength',
        group='Denoise And Noise Maps',
        default='0.5',
        metavar='S[,S...]',
        family='denoise',
        key='strength',
        help='Denoise strength 0..1 (default 0.5); with a chained --denoise, give one value per stage (comma list) or one value for all. For mc, the max temporal blend toward motion-compensated history; for spatial, the noise level; for fastdvdnet/bsvd, the noise sigma (mapped onto sigma_255 in [5, 55]). For toflow, a dry/wet output blend (0 = passthrough, 1 = full model). With --noise-map auto the estimated map REPLACES this constant (strength then only serves as the fallback when estimation is impossible); scale the estimate with --noise-map-gain instead.'),
    Opt(flag='--denoise-luma-strength',
        group='Denoise And Noise Maps',
        type=float,
        default=1.0,
        metavar='A',
        family='denoise',
        key='luma_strength',
        help='Luma half of --denoise: blend strength for the luma channel between the input and the denoiser output. 1.0 = full denoise (default); lower keeps original luma texture. Split from --denoise-chroma-strength via a BT.601 recombine (works with any --denoise backend), so you can preserve luma detail while still cleaning chroma. >1 over-drives.'),
    Opt(flag='--denoise-chroma-strength',
        group='Denoise And Noise Maps',
        type=float,
        default=1.0,
        metavar='A',
        family='denoise',
        key='chroma_strength',
        help='Chroma half of --denoise: blend strength for the chroma channels. 1.0 = full (default). The standard split is a low --denoise-luma-strength with this at 1.0 (aggressive chroma NR, gentle luma -- the eye barely sees chroma detail). <1 keeps original chroma noise.'),
]

UPSCALE_SLOT_OPTIONS = [
    Opt(flag='--upscale',
        group='Spatial Upscalers',
        default='balanced',
        choices=('fast', 'balanced', 'image', 'none', 'basicvsrpp', 'realbasicvsr', 'realesrgan', 'safmn', 'esc', 'realviformer', 'realplksr', 'toflow', 'metalfx'),
        help="VSR spatial mode.  Scale factor is implied by the mode (fast=2x, balanced=4x, image=4x, none=1x, basicvsrpp=4x, realbasicvsr=4x, realesrgan=4x, safmn=4x, esc=4x, realviformer=4x, realplksr=2x/4x, toflow=4x, metalfx=2x/3x/4x via --metalfx-scale). metalfx = Apple's MetalFX spatial scaler (the game upscaler network, shipped in the OS -- no weights to download). By far the cheapest learned upscale (~1 ms/frame at 320x180 -> 4x, ~20x cheaper than image/balanced) with edge sharpness close to VT image quality; the trade is content-dependent texture synthesis -- it invents plausible high-frequency detail, which reads as crisp on structured content and as a subtle crawl on stochastic texture (sand, brick, foliage). Per-frame, no temporal state. realplksr = MLX RealPLKSR per-frame SR (Phhofm checkpoints; scale from the checkpoint -- nomos4x is 4x, public2x is 2x). Single-image, no pooled modulation gate so it cannot produce SAFMN's block lattice; choose the checkpoint with --realplksr-profile. realesrgan = MLX Real-ESRGAN / ESRGAN RRDBNet 4x per-frame SR (single-image: no temporal propagation, so no flow ghosting; choose the checkpoint with --realesrgan-profile). basicvsrpp = MLX BasicVSR++ 4x super-resolution (recurrent, learned); toflow = MLX TOFlow SR 4x (seven-frame task-oriented-flow SR; expects bicubic-upsampled LR and predicts a residual over the center frame); realbasicvsr = MLX RealBasicVSR 4x real-world video SR with an iterative cleaning stage before BasicVSR propagation; runs on the GPU via MLX instead of VideoToolbox, processed in sliding windows (see the model-specific --*-window/--*-trim flags). Slower than the VT modes but uses learned SR checkpoints. none = no super-resolution; output stays at native resolution. Use it with --denoise to denoise-only, or alone for a plain transcode. balanced (default) = HQ Video mode; uses prev source + prev output frames to inform the upscale.  Tends to produce crisper motion edges at the cost of slightly more frame-to-frame variation in detail. fast = VTLowLatency 2x scaler.  Per-frame, no temporal context.  Input must be 96x96 to 960x960. image = HQ Image mode.  Per-frame deterministic upscale with no prev-frame feedback.  Slightly softer per-frame detail than balanced, but measurably smoother frame-to-frame (lower temporal second-difference). Apple documents this as for stills; on video it's a legitimate alternative to balanced if you prefer the smoother trade-off."),
]

RUNTIME_OPTIONS = [
    Opt(flag='--probe-noise',
        group='Runtime And Diagnostics',
        kind='flag',
        default=False,
        help="Analyze the clip's noise instead of processing it: per-block quantile/energy/amplitude sigma statistics, flicker density and amplitude, temporal persistence, edge/luma correlation, a static-grain proxy, per-channel split, and the per-frame flash trace with keyframe distances. Three sample windows across the trim range; prints and exits. Same analysis as `kinovsr probe noise`."),
    Opt(flag='--video-chunk-size',
        group='Runtime And Diagnostics',
        type=int,
        default=32,
        help='Upper bound on decoded frames held in flight for --video input. The actual chunk is further capped to a ~64 MiB memory budget based on resolution, so peak resident decode memory stays bounded (often 1 frame at 4K, this many at SD).'),
    Opt(flag='--mlx-cache-limit-gb',
        group='Runtime And Diagnostics',
        type=float,
        settings_backed=True,
        help="Cap MLX's buffer cache (GB) so per-frame allocation churn does not grow into swap; 0 disables. Default 1.0."),
]

__all__ = [
    "SOURCE_AND_OUTPUT_OPTIONS",
    "PREPROCESS_SLOT_OPTIONS",
    "DEBLOCK_SLOT_OPTIONS",
    "DEBLOCK_STRENGTH_OPTIONS",
    "DENOISE_SLOT_OPTIONS",
    "UPSCALE_SLOT_OPTIONS",
    "RUNTIME_OPTIONS",
]
