"""Generate docs/PROCESSORS.md from the manifest registry.

The matrix is derived data: every row comes from the same manifests that
`kinovsr weights list|verify` read, so the doc cannot drift from the
machine-readable truth without this script noticing. Regenerate after any
manifest change:

    python scripts/dev/gen_processor_matrix.py

The doc records static facts only (profiles, capabilities, assets,
distribution, license, source). Presence on a given machine is deliberately
excluded; that is `kinovsr weights verify`'s job.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "PROCESSORS.md"

HEADER = """\
# Processors, profiles, and weights

<!-- Generated by scripts/dev/gen_processor_matrix.py; edit manifests, not
     this file. Regenerate after any manifest change. -->

Every learned family ships a machine-readable manifest naming its profiles,
capabilities, and weight artifacts. This matrix is generated from those
manifests. Weights are not bundled unless marked so; each family's
`weights/README.md` documents how to obtain and convert them
(`kinovsr weights convert`), and `weights/Attribution.md` carries the
upstream credit. Check what is installed locally with:

```bash
kinovsr weights list
kinovsr weights verify
```
"""


def _owner_section(owner: str, manifest) -> list[str]:
    lines = [f"## {owner} ({manifest.kind})", ""]
    if manifest.profiles:
        lines.append("| profile | capabilities | weights |")
        lines.append("| --- | --- | --- |")
        for name in manifest.profiles:
            profile = manifest.profiles[name]
            caps = ", ".join(profile.capabilities) or "-"
            weights = ", ".join(profile.weights) or "-"
            lines.append(f"| `{name}` | {caps} | {weights} |")
        lines.append("")
    lines.append("| asset | distribution | license | source |")
    lines.append("| --- | --- | --- | --- |")
    for asset_id in manifest.weights:
        asset = manifest.weights[asset_id]
        license_note = asset.license or "-"
        source = asset.source or "-"
        if source.startswith(("http://", "https://")):
            url, separator, suffix = source.partition(" ")
            source = f"<{url}>{separator}{suffix}"
        lines.append(
            f"| `{asset_id}` ({asset.path.name}) | {asset.distribution} "
            f"| {license_note} | {source} |")
    lines.append("")
    return lines


def main() -> int:
    sys.path.insert(0, str(REPO))
    from kinovsr.modeling.weights import load_registered, registered_owners

    lines = [HEADER.rstrip(), ""]
    by_kind: dict[str, list[str]] = {}
    for owner in registered_owners():
        manifest = load_registered(owner)
        by_kind.setdefault(manifest.kind, []).append(owner)
    # Processor families first: they are what a user selects; shared
    # components and evaluators are supporting casts.
    order = ["processor", "component", "evaluator"]
    kinds = order + sorted(set(by_kind) - set(order))
    for kind in kinds:
        for owner in by_kind.get(kind, ()):
            lines.extend(_owner_section(owner, load_registered(owner)))
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
