"""CLI option rows owned by the TOFlow family."""

from kinovsr.cli.options import Opt

TOFLOW_STRENGTH_OPTIONS = [
    Opt(flag='--toflow-strength',
        group='Denoise And Noise Maps',
        type=float,
        metavar='S',
        family='toflow',
        key='strength',
        stage_capabilities=('denoise', 'deblock'),
        help='Strength for toflow in the --denoise or --deblock chain (dry/wet output blend), overriding the positional chain value for this family (default: the chain value).'),
]

TOFLOW_OPTIONS = [
    Opt(flag='--toflow-profile',
        group='Denoise And Noise Maps',
        default='denoise',
        choices=('denoise', 'deblock'),
        family='toflow',
        key='profile',
        stage_capabilities=('denoise', 'deblock'),
        help='Which converted TOFlow model for --denoise toflow. denoise (default) is the seven-frame video denoiser; deblock uses the released TOFlow deblocking checkpoint in the same seven-frame runtime shape. Ignored when --toflow-weights points at a specific converted checkpoint.'),
    Opt(flag='--toflow-weights',
        group='Denoise And Noise Maps',
        metavar='PATH',
        family='toflow',
        key='weights',
        stage_capabilities=('denoise', 'deblock'),
        settings_backed=True,
        help='Override TOFlow weights (.safetensors) for --denoise toflow. Optional - defaults to the local --toflow-profile weights (or $TOFLOW_WEIGHTS). Convert a .t7 with kinovsr/processors/toflow/convert_t7_to_safetensors.py.'),
    Opt(flag='--toflow-graph',
        group='Denoise And Noise Maps',
        metavar='PATH',
        family='toflow',
        key='graph',
        stage_capabilities=('denoise', 'deblock'),
        settings_backed=True,
        help='Override TOFlow graph JSON for --denoise toflow (or $TOFLOW_GRAPH). Default: same stem as --toflow-weights with .json suffix.'),
    Opt(flag='--toflow-dtype',
        group='Denoise And Noise Maps',
        default='float32',
        choices=('float16', 'float32'),
        family='toflow',
        key='dtype',
        stage_capabilities=('denoise', 'deblock'),
        help='MLX dtype for --denoise toflow (default float32; float16 is faster but less parity-faithful).'),
    Opt(flag='--toflow-passes',
        group='Denoise And Noise Maps',
        type=int,
        default=1,
        metavar='N',
        family='toflow',
        key='passes',
        stage_capabilities=('denoise', 'deblock'),
        help='Run TOFlow N times back to back INSIDE one stage (equivalent to chaining toflow N times, measured within 0.01 dB / ~55 dB agreement) but computing the flow only once: deblock passes do not move content, so the flow is pass-invariant and later passes pay only warp + fusion. Measured: 3 passes at quarter flow run 59 ms/frame at 480x360 vs 93 for the explicit chain. Latency is 3*N frames. Iteration deepens the cleaning at ~0.3 dB fidelity per extra pass (PSNR charges smoothing).'),
    Opt(flag='--toflow-flow-scale',
        group='Denoise And Noise Maps',
        default='full',
        choices=('full', 'half', 'quarter'),
        family='toflow',
        key='flow_scale',
        stage_capabilities=('denoise', 'deblock'),
        help="Resolution of TOFlow's internal flow pyramid (denoise/deblock slots). full (default) = the faithful network. half = skip the full-resolution flow refinement level, the dominant cost of the whole net: measured 3.3x faster (229 -> 71 ms/frame at 480x360) for -0.2 to -0.4 dB on crushed ground-truth fixtures. quarter = also skip the half-res level: 31 ms/frame (7x), nearly free beyond half on static-camera content. Both bills were measured on static-ish fixtures -- coarse flow pays its real cost on FAST motion (misaligned neighbors soften the fusion), so eyeball moving content before relying on them for delivery."),
]

TOFLOW_UPSCALE_OPTIONS = [
    Opt(flag='--toflow-sr-weights',
        group='Denoise And Noise Maps',
        metavar='VARIANT|PATH',
        family='toflow_sr',
        key='weights',
        stage_processor='toflow',
        stage_capabilities=('upscale',),
        settings_backed=True,
        help='TOFlow SR weights for --upscale toflow: the bundled sr token or a .safetensors path (or $TOFLOW_SR_WEIGHTS). This is the released task-oriented-flow SR checkpoint converted from sr.t7.'),
    Opt(flag='--toflow-sr-graph',
        group='Denoise And Noise Maps',
        metavar='PATH',
        family='toflow_sr',
        key='graph',
        stage_processor='toflow',
        stage_capabilities=('upscale',),
        settings_backed=True,
        help='Override TOFlow SR graph JSON for --upscale toflow (or $TOFLOW_SR_GRAPH). Default: same stem as --toflow-sr-weights with .json suffix.'),
    Opt(flag='--toflow-sr-dtype',
        group='Denoise And Noise Maps',
        default='float32',
        choices=('float16', 'float32'),
        family='toflow_sr',
        key='dtype',
        stage_processor='toflow',
        stage_capabilities=('upscale',),
        help='MLX dtype for --upscale toflow (default float32; float16 is faster but less parity-faithful).'),
]

__all__ = ["TOFLOW_STRENGTH_OPTIONS", "TOFLOW_OPTIONS", "TOFLOW_UPSCALE_OPTIONS"]
