"""CLI option rows owned by the RealBasicVSR family."""

from kinovsr.cli.options import Opt

REALBASICVSR_OPTIONS = [
    Opt(flag='--realbasicvsr-weights',
        group='Spatial Upscalers',
        metavar='PATH',
        family='realbasicvsr',
        key='weights',
        settings_backed=True,
        help="RealBasicVSR weights path (.safetensors) for --upscale realbasicvsr (or $REALBASICVSR_WEIGHTS). Convert a .pth with kinovsr weights convert --only-prefix generator_ema. --strip-prefix generator_ema."),
    Opt(flag='--realbasicvsr-profile',
        group='Spatial Upscalers',
        choices=('x4',),
        family='realbasicvsr',
        key='profile',
        help='Which RealBasicVSR model for --upscale realbasicvsr (x4 = the released real-world 4x checkpoint, default). Ignored when --realbasicvsr-weights is given.'),
    Opt(flag='--realbasicvsr-window',
        group='Spatial Upscalers',
        type=int,
        default=14,
        metavar='N',
        family='realbasicvsr',
        key='window',
        help='Sliding-window length (frames) for --upscale realbasicvsr (default 14). Larger = more temporal context, but more memory + compute.'),
    Opt(flag='--realbasicvsr-trim',
        group='Spatial Upscalers',
        type=int,
        default=0,
        metavar='N',
        family='realbasicvsr',
        key='trim',
        help='Warm-up frames trimmed at each window join for --upscale realbasicvsr (default 0, matching the reference max_seq_len non-overlap chunking). Values >0 re-run overlapping windows and discard boundary frames, which costs more compute.'),
    Opt(flag='--realbasicvsr-clean-threshold',
        group='Spatial Upscalers',
        type=float,
        default=5.0,
        metavar='V',
        family='realbasicvsr',
        key='clean_threshold',
        help='RealBasicVSR cleaning stop threshold in 0..255 units (default 5, the GAN test-time setting; 255 forces one cleaning pass).'),
    Opt(flag='--realbasicvsr-clean-iters',
        group='Spatial Upscalers',
        type=int,
        default=3,
        metavar='N',
        family='realbasicvsr',
        key='clean_iters',
        help='Maximum RealBasicVSR cleaning passes before propagation (default 3).'),
    Opt(flag='--realbasicvsr-residual-strength',
        group='Spatial Upscalers',
        type=float,
        default=1.0,
        metavar='V',
        family='realbasicvsr',
        key='residual_strength',
        help='Scale the learned RealBasicVSR residual before adding it to the 4x bilinear base (default 1.0). Try 0.6-0.85 to reduce GAN/pixel-shuffle lattice artifacts on moving objects while retaining most sharpening.'),
    Opt(flag='--realbasicvsr-flow-consistency',
        group='Spatial Upscalers',
        type=float,
        default=0.0,
        metavar='S',
        family='realbasicvsr',
        key='flow_consistency',
        help="Forward-backward flow-consistency masking strength in 0..1 for --upscale realbasicvsr (default 0 = off, reference behavior). Down-weights the recurrent feature where the optical-flow round-trip fails -- occlusions and fast-moving regions (panning backgrounds, objects/people passing, body edges) -- cutting propagation ghosting there while keeping detail on well-aligned regions. Note: it does NOT fix ghosting on a stable subject with consistent-but-wrong flow (a selfie face's specular highlights); use --realbasicvsr-window 1 for that. Try 0.7-1.0."),
    Opt(flag='--realbasicvsr-flow',
        group='Spatial Upscalers',
        default='spynet',
        choices=('spynet', 'zero', 'vt', 'vision'),
        family='realbasicvsr',
        key='flow',
        help='Optical-flow source for --upscale realbasicvsr (default spynet). zero disables motion compensation while keeping recurrent propagation, as a control for flow-painted temporal artifacts. vt uses VTOpticalFlow (Quality tier, self-tested at startup; smooth fields, no content-shaped flow noise). vision uses Vision optical flow revision 1 (Medium accuracy, pinned; self-tested at startup) -- the best measured flow backend: sharper true motion than vt at a fraction of its latency, accurate at small sizes where vt collapses, and off the MLX GPU queue.'),
    Opt(flag='--realbasicvsr-history-strength',
        group='Spatial Upscalers',
        type=float,
        default=1.0,
        metavar='S',
        family='realbasicvsr',
        key='history_strength',
        help="Scale RealBasicVSR's propagated features before each trunk (default 1.0 = reference strength). 0 disables temporal propagation entirely (per-frame within the cleaning + upsampler)."),
    Opt(flag='--realbasicvsr-history-gate',
        group='Spatial Upscalers',
        default='off',
        choices=('off', 'improve'),
        family='realbasicvsr',
        key='history_gate',
        help="Per-pixel history admission for RealBasicVSR's propagation (default off = reference behavior). improve admits warped history only where the flow warp measurably improves the photometric residual against the current cleaned frame -- the mitigation for the window>1 propagation smear (dark ghosting trails around faces/movers); regions the flow cannot explain fall back to the trained window-start (zero history) behavior."),
]

__all__ = ["REALBASICVSR_OPTIONS"]
